### ISSUE TITLE
BUG: No matching distribution found for feo-client==0.0.1a8

### ISSUE THREAD

**Issue by abhishek0208** [transition-zero/feo-client-examples#13]
### Checklist

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of feo-client-examples.

- [X] I have confirmed this bug exists on the main branch of feo-client-examples.

### Reproducible Example

`!pip install --extra-index-url https://test.pypi.org/simple/ feo-client==0.0.1a8`

### Issue Description

```
Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple/
ERROR: Ignored the following yanked versions: 0.0.0
ERROR: Could not find a version that satisfies the requirement feo-client==0.0.1a8 (from versions: 0.0.1a4, 0.0.1a6, 0.0.1a7)
ERROR: No matching distribution found for feo-client==0.0.1a8
```

### Expected Behavior

`feo-client` version `0.0.1a8` isn't yet included in the available versions

**Comment by joconnor-ecaa** [comment]
This was a placeholder that has now been released, sorry!

https://github.com/transition-zero/feo-client/releases/tag/v0.0.1-alpha8

**Comment by joconnor-ecaa** [comment]
Go ahead and close if this fixes

**Comment by abhishek0208** [comment]
Fixed with new release
