### ISSUE TITLE
BUG: Node.assets returning assets not in Node. 

### ISSUE THREAD

**Issue by Tomkourou** [transition-zero/feo-client-examples#15]
### Checklist

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of feo-client-examples.

- [X] I have confirmed this bug exists on the main branch of feo-client-examples.

### Reproducible Example

IDN = Node.from_id("IDN")
IDN.assets

### Issue Description

id | node_type | type_alias | name_primary_en | public | is_asset | properties | sector | parents | children | ... | capacity | capacity_unit | start_date | retired_date | technology_detail | has_ccs | is_captive | captive_detail | other_ids_names | ownership_details
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PWRURNAREA0U0 | power_unit | powerUnit | Barakah nuclear power plant - 1 | True | True | {'gem_admin_0': 'United Arab Emirates', 'gem_a... | power | None | None | ... | 1417.0 | MW | 2021-01-01 | None | {'model_type': 'Apr-1400', 'reactor_type': 'pr... | None | False | {} | {'gem_unit_id': 'G500018', 'gem_asset_id': 'L5... | {'owner': 'Emirates Nuclear Energy Corporation...
PWRURNAREA0U1 | power_unit | powerUnit | Barakah nuclear power plant - 3 | True | True | {'gem_admin_0': 'United Arab Emirates', 'gem_a... | power | None | None | ... | 1400.0 | MW | 2022-01-01 | None | {'model_type': 'Apr-1400', 'reactor_type': 'pr... | None | False | {} | {'gem_unit_id': 'G500020', 'gem_asset_id': 'L5... | {'owner': 'Emirates Nuclear Energy Corporation...
PWRURNAREA0U2 | power_unit | powerUnit | Barakah nuclear power plant - 2 | True | True | {'gem_admin_0': 'United Arab Emirates', 'gem_a... | power | None | None | ... | 1417.0 | MW | 2022-01-01 | None | {'model_type': 'Apr-1400', 'reactor_type': 'pr... | None | False | {} | {'gem_unit_id': 'G500022', 'gem_asset_id': 'L5... | {'owner': 'Emirates Nuclear Energy Corporation...
PWRURNAREA0U3 | power_unit | powerUnit | Barakah nuclear power plant - 4 | True | True | {'gem_admin_0': 'United Arab Emirates', 'gem_a... | power | None | None | ... | 1400.0 | MW | 2023-01-01 | None | {'model_type': 'Apr-1400', 'reactor_type': 'pr... | None | False | {} | {'gem_unit_id': 'G500021', 'gem_asset_id': 'L5... | {'owner': 'Emirates Nuclear Energy Corporation...
PWRURNARGA0U0 | power_unit | powerUnit | Atucha nuclear power plant - 1 | True | True | {'gem_admin_0': 'Argentina', 'gem_admin_1': 'B... | power | None | None | ... | 362.0 | MW | 1974-01-01 | None | {'model_type': 'PHWR KWU', 'reactor_type': 'pr... | None | False | {} | {'gem_unit_id': 'G500502', 'gem_asset_id': 'L5... | {'owner': 'Nucleoelectrica Argentina SA', 'ope...
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...
PWRGASIRQA72U3 | power_unit | powerUnit | Baghdad South Combined Cycle power plant - GT-6 | True | True | {'gem_admin_0': 'Iraq', 'gem_admin_1': 'Baghda... | power | None | None | ... | 125.0 | MW | 2024-01-01 | None | {'technology_type': 'gt'} | None | False | {} | {'gem_unit_id': 'G411631', 'gem_asset_id': 'L4... | {'owner': 'Ministry of Electricity (Iraq)', 'p...
PWRGASIRQA72U4 | power_unit | powerUnit | Baghdad South Combined Cycle power plant - GT-5 | True | True | {'gem_admin_0': 'Iraq', 'gem_admin_1': 'Baghda... | power | None | None | ... | 125.0 | MW | 2024-01-01 | None | {'technology_type': 'gt'} | None | False | {} | {'gem_unit_id': 'G411632', 'gem_asset_id': 'L4... | {'owner': 'Ministry of Electricity (Iraq)', 'p...
PWRGASIRQA72U5 | power_unit | powerUnit | Baghdad South Combined Cycle power plant - GT-4 | True | True | {'gem_admin_0': 'Iraq', 'gem_admin_1': 'Baghda... | power | None | None | ... | 125.0 | MW | 2024-01-01 | None | {'technology_type': 'gt'} | None | False | {} | {'gem_unit_id': 'G411633', 'gem_asset_id': 'L4... | {'owner': 'Ministry of Electricity (Iraq)', 'p...
PWRGASIRQA72U6 | power_unit | powerUnit | Baghdad South Combined Cycle power plant - GT-3 | True | True | {'gem_admin_0': 'Iraq', 'gem_admin_1': 'Baghda... | power | None | None | ... | 125.0 | MW | 2024-01-01 | None | {'technology_type': 'gt'} | None | False | {} | {'gem_unit_id': 'G411634', 'gem_asset_id': 'L4... | {'owner': 'Ministry of Electricity (Iraq)', 'p...
PWRGASIRQA72U7 | power_unit | powerUnit | Baghdad South Combined Cycle power plant - GT-2 | True | True | {'gem_admin_0': 'Iraq', 'gem_admin_1': 'Baghda... | power | None | None | ... | 125.0 | MW | 2024-01-01 | None | {'technology_type': 'gt'} | None | False | {} | {'gem_unit_id': 'G411635', 'gem_asset_id': 'L4... | {'owner': 'Ministry of Electricity (Iraq)', 'p...

<p style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin-bottom: 6px; margin-top: 6px; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px;">10000 rows × 25 columns</p>

### Expected Behavior

I would expect that calling IDN.assets only returns assets within Indonesia.

**Comment by joconnor-ecaa** [comment]
I'm going to move this to `feo-client`
